from rply import LexerGenerator
lg = LexerGenerator()
lg.ignore('\s+')

lg.add('PLUS', r'\+')
lg.add('MINUS', r'-')
lg.add('MUL', r'\*')
lg.add('DIV', r'/')
lg.add('OPEN_PARENS', r'\(')
lg.add('CLOSE_PARENS', r'\)')
lg.add('keyINT', r'int')
lg.add('keyFLOAT', r'float')
lg.add('keyDOUBLE', r'double')
lg.add('keySTRING', r'string')
lg.add('keyBOOL', r"bool")
lg.add('INT', r'[0-9][0-9]*')
lg.add('FLOAT', r'[0-9].[0-9]]')
lg.add('DOUBLE', r'double')
lg.add('STRING', r'".*"')
lg.add('CHAR', r"'.'")
lg.add('BOOL', r"true")
lg.add('BOOL', r"false")
lg.add('OPEN_ANGLE', r'<')
lg.add('CLOSE_ANGLE', r'>')
lg.add('ASSIGN',r'=')
lg.add('VARIABLE' , r'[a-zA-Z][0-9a-zA-Z_]*')
lexer = lg.build()

